// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfLFbxk0CUlNt09VinCnVKte_Z4vUwsO4',
    appId: '1:208943284636:web:6ec8d56bcb6762d37cc859',
    messagingSenderId: '208943284636',
    projectId: 'tuan-4-shop',
    authDomain: 'tuan-4-shop.firebaseapp.com',
    storageBucket: 'tuan-4-shop.firebasestorage.app',
    measurementId: 'G-JH3NBRNTTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzhXn2J_OSsjergqitZiA3xNeSHrPBjog',
    appId: '1:208943284636:android:11cb1fb08680d5a37cc859',
    messagingSenderId: '208943284636',
    projectId: 'tuan-4-shop',
    storageBucket: 'tuan-4-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7cERHM-GAYv9weRiOW0u9S1UiVetQPfg',
    appId: '1:208943284636:ios:5ad73a745fcc73d77cc859',
    messagingSenderId: '208943284636',
    projectId: 'tuan-4-shop',
    storageBucket: 'tuan-4-shop.firebasestorage.app',
    iosBundleId: 'com.example.tuan4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7cERHM-GAYv9weRiOW0u9S1UiVetQPfg',
    appId: '1:208943284636:ios:5ad73a745fcc73d77cc859',
    messagingSenderId: '208943284636',
    projectId: 'tuan-4-shop',
    storageBucket: 'tuan-4-shop.firebasestorage.app',
    iosBundleId: 'com.example.tuan4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfLFbxk0CUlNt09VinCnVKte_Z4vUwsO4',
    appId: '1:208943284636:web:27cc5817846f9c5c7cc859',
    messagingSenderId: '208943284636',
    projectId: 'tuan-4-shop',
    authDomain: 'tuan-4-shop.firebaseapp.com',
    storageBucket: 'tuan-4-shop.firebasestorage.app',
    measurementId: 'G-MS8NS3GEQJ',
  );
}
